### ISSUE TITLE
Slack Adapter not starting

### ISSUE THREAD

**Issue by officebluesource** [rajivrnair/upsource-slack-api-adapter#24]
Hi,

Tried to start with npm start, the following error appears (log output):

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.10.3
3 info using node@v12.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle slack-upsource-translator@0.0.1~prestart: slack-upsource-translator@0.0.1
6 info lifecycle slack-upsource-translator@0.0.1~start: slack-upsource-translator@0.0.1
7 verbose lifecycle slack-upsource-translator@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle slack-upsource-translator@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/upsource-slack/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle slack-upsource-translator@0.0.1~start: CWD: /opt/upsource-slack
10 silly lifecycle slack-upsource-translator@0.0.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle slack-upsource-translator@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle slack-upsource-translator@0.0.1~start: Failed to exec start script
13 verbose stack Error: slack-upsource-translator@0.0.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid slack-upsource-translator@0.0.1
15 verbose cwd /opt/upsource-slack
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.8.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error slack-upsource-translator@0.0.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the slack-upsource-translator@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

regards,
Michael

**Comment by vivchar** [comment]
I have similar problem:

```
bash-3.2$ npm start

> slack-upsource-translator@0.0.1 start /Users/vvv/Documents/upsource-slack-api-adapter
> node index.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'request'
Require stack:
- /Users/vvv/Documents/upsource-slack-api-adapter/adapters/review-created-feed-event.js
- /Users/vvv/Documents/upsource-slack-api-adapter/adapters/index.js
- /Users/vvv/Documents/upsource-slack-api-adapter/app.js
- /Users/vvv/Documents/upsource-slack-api-adapter/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/vvv/Documents/upsource-slack-api-adapter/adapters/review-created-feed-event.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/vvv/Documents/upsource-slack-api-adapter/adapters/review-created-feed-event.js',
    '/Users/vvv/Documents/upsource-slack-api-adapter/adapters/index.js',
    '/Users/vvv/Documents/upsource-slack-api-adapter/app.js',
    '/Users/vvv/Documents/upsource-slack-api-adapter/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slack-upsource-translator@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slack-upsource-translator@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vvv/.npm/_logs/2019-09-25T04_51_25_302Z-debug.log
```
